[tool.black]
exclude = "migrations"

[tool.isort]
skip = "migrations"

[tool.poetry]
name = "qupiya"
version = "0.3.0"
description = "ğŸ” Yet yet another another password managing app"
authors = ["Dastan Ozgeldi <ozgdastan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"
Flask-SQLAlchemy = "^2.5.1"
Flask-WTF = "^1.0.0"
Flask-Migrate = "^3.1.0"
Flask-Login = "^0.5.0"
Flask-Bcrypt = "^0.7.1"
python-dotenv = "^0.19.2"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^22.1.0"
isort = "^5.10.1"
gunicorn = "^20.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
